// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using OOAD.Data;
using System;

namespace OOAD.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180415194757_AddEquipmentDBSet")]
    partial class AddEquipmentDBSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("OOAD.Models.Equipments", b =>
                {
                    b.Property<int>("E_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("E_amount");

                    b.Property<string>("E_name");

                    b.Property<int>("E_total");

                    b.HasKey("E_ID");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("OOAD.Models.EquipmentsRent", b =>
                {
                    b.Property<int>("Rent_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("E_ID");

                    b.Property<int>("Rent_by");

                    b.Property<string>("Rent_time");

                    b.HasKey("Rent_ID");

                    b.ToTable("EquipmentsRent");
                });

            modelBuilder.Entity("OOAD.Models.EquipmentsReserve", b =>
                {
                    b.Property<int>("Resv_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("E_ID");

                    b.Property<int>("Resv_by");

                    b.Property<string>("Resv_time");

                    b.HasKey("Resv_ID");

                    b.ToTable("EquipmentsReserve");
                });

            modelBuilder.Entity("OOAD.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Faculty");

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Role");

                    b.Property<string>("StudentId");

                    b.Property<string>("Telephon");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OOAD.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
